from abc import ABC, abstractmethod

class BaseSpeaker(ABC):
    def __init__(self) -> None:
        super().__init__()

    @property
    @abstractmethod
    def voice(self):
        return self.__voice

    @voice.setter
    @abstractmethod
    def voice(self, value):
        """All concrete classes must implement a voice setter to change the 
        voice the speaker generation will use. This will take a langauge
        ISO code and make any necessary modifications to the speaker model etc. 
        in order to generate a voice in the new langauge"""

    @abstractmethod
    def say(self, input, wait4prev):
        """All concrete classes must implement the say method
        that is used to play speech generated by the "generate" method
        for the provided text. Blocks until the playing of the generated 
        audio is complete if wait4prev is True"""
        pass

    @abstractmethod
    def generate(self, output):
        """All concrete classes must implement the generate method
        that is used to generates audio and returns a structure to
        be played by the say method"""
        pass

    @classmethod
    def supported_lang(cls, lang=False):
        """All concrete classes must implement a way to check whether
        a language is supported that does not require instancing the class
        returning either True or False for the provided language"""
        return lang